/**
 * Vitest global setup — points the integration suite at committed
 * shadcn-init fixtures so `scaffoldViaShadcn{Monorepo,Flat}` can copy
 * from a known-good directory tree instead of spawning a real
 * `pnpm dlx shadcn@latest init …` per test (~12-18s per call, network
 * round-trip).
 *
 * Fixtures live at `tests/fixtures/shadcn-{monorepo,flat}-init/` and
 * are checked into the repo. They were generated by running shadcn's
 * monorepo + flat init flows once locally (see
 * `tools/refresh-shadcn-fixtures.sh`); refresh whenever shadcn ships a
 * b0-preset change that affects our augmentation pipeline.
 *
 * scaffoldViaShadcn{Monorepo,Flat} (in src/index.ts) detect the
 * NEXT_MCP_SHADCN_*_FIXTURE env vars set here and copy from the
 * fixtures. The augmentation pipeline (rename, catalog, alignPins,
 * etc.) runs on the copy so the resulting workspace is identical to
 * what a live init would produce.
 *
 * The smoke driver (`tools/smoke.ts`) does NOT consume these env vars
 * — `pnpm run smoke` always invokes a real shadcn init as the canonical
 * runtime check. Run smoke periodically to catch fixture drift.
 */
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MONOREPO_FIXTURE = path.resolve(__dirname, 'fixtures/shadcn-monorepo-init');
const FLAT_FIXTURE = path.resolve(__dirname, 'fixtures/shadcn-flat-init');

export async function setup(): Promise<void> {
  if (existsSync(MONOREPO_FIXTURE)) {
    process.env.NEXT_MCP_SHADCN_MONOREPO_FIXTURE = MONOREPO_FIXTURE;
  }
  if (existsSync(FLAT_FIXTURE)) {
    process.env.NEXT_MCP_SHADCN_FLAT_FIXTURE = FLAT_FIXTURE;
  }
}

export async function teardown(): Promise<void> {
  // No-op: committed fixtures are not mutated.
}
